### ISSUE TITLE
401 error on clean installation

### ISSUE THREAD

**Issue by zchef2k** [utterance/utterances-oauth#4]
I have just deployed a fresh instance of utterances and utterances-oauth and am getting this in my response "/token"

"token" cookie is required.

I've got everything setup to the self-hosting instructions. What am I missing or has something in the code changed recently?

**Comment by jdanyow** [comment]
Is there a url you can share?

**Comment by zchef2k** [comment]
I don't unfortunately, Everything is internal. I suspect it has something to do with OAuth flow. It seems to coincide with a warning about redirect_uri not matching. I'll try to furnish some screenshots a bit later.

**Comment by zchef2k** [comment]
I believe the 401 is normal behavior when the utterances iframe loads until the user logs in. This based on what I see in https://utteranc.es. 

I will mark this as closed.
